export const homeFormSubmit = [
  {
    operandIdentifier: 1,
    address: 6.0,
    name: "F_True",
    dataType: "BOOL",
    comment: "Inbetriebnahmebr�cke",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 85.4,
    name: "1IB1I01SFWE7",
    dataType: "BOOL",
    comment: "E7-�berbr�ckung Verriegelung Nebenbedienpult",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 62.1,
    name: "1IB1KFS1SFN1",
    dataType: "BOOL",
    comment: "Not-Halt Comfort Panel",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 512.0,
    name: "11HP1VI1KKP01EE",
    dataType: "BOOL",
    comment: "Einschaltventil ein",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 512.2,
    name: "11HP1VI1KKP01DE",
    dataType: "BOOL",
    comment: "Luft ein",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 512.3,
    name: "11HP1VI1KKP01DA",
    dataType: "BOOL",
    comment: "Luft aus",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 512.4,
    name: "11HP1VI1KKP01WE",
    dataType: "BOOL",
    comment: "K�hlwasser ein",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 512.5,
    name: "11HP1VI1KKP01WA",
    dataType: "BOOL",
    comment: "K�hlwasser aus",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 513.0,
    name: "11HP1VI1KKP01EBER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 513.1,
    name: "11HP1VI1KKP01DBER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 513.2,
    name: "11HP1VI1KKP01WBER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 516.0,
    name: "11HP1VI1BP01E",
    dataType: "BOOL",
    comment: "Kontrolle Einschaltventil",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 516.2,
    name: "11HP1BP01ND",
    dataType: "BOOL",
    comment: "Kontrolle Niederdruck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 516.4,
    name: "11HP1BF01NDIMP",
    dataType: "BOOL",
    comment: "Impuls",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 516.6,
    name: "11HP1BP01HD",
    dataType: "BOOL",
    comment: "Kontrolle Hochdruck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 517.0,
    name: "11HP1BF01HDIMP",
    dataType: "BOOL",
    comment: "Impuls",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 532.0,
    name: "113450V01VI2KKPR01V",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 532.1,
    name: "113450V01VI2KKPR01R",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 532.2,
    name: "113450V01VI2KKPR02V",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 532.3,
    name: "113450V01VI2KKPR02R",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 533.0,
    name: "113450V01VI2KKPR01BER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 533.1,
    name: "113450V01VI2KKPR02BER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 522.6,
    name: "113450V01VI1KKPR01V",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 522.7,
    name: "113450V01VI1KKPR01R",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 523.0,
    name: "113450V01VI1KKPR02V",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 523.1,
    name: "113450V01VI1KKPR02R",
    dataType: "BOOL",
    comment: "RESERVE",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 523.3,
    name: "113450V01VI1KKPR01BER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 523.4,
    name: "113450V01VI1KKPR02BER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 523.5,
    name: "113450SB1VI1KKPR01BER",
    dataType: "BOOL",
    comment: "Ventil bereit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 82.0,
    name: "113440R01PFWE7",
    dataType: "BOOL",
    comment: "E7 �berbr�ckung Schutzkreis",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 130.1,
    name: "113440R01KF1K36",
    dataType: "BOOL",
    comment: "Schutzkreis f�r Schwenkeinheit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 56.2,
    name: "113440R01SFWE7",
    dataType: "BOOL",
    comment: "E7 Prozessgeschwindigkeit bei Single-Step",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 142.1,
    name: "113440R01KF1K36K",
    dataType: "BOOL",
    comment: "R�ckleseeingang Relaismodul",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 82.0,
    name: "11IG1SFRES1",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 82.1,
    name: "11IG1SFRES2",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 82.2,
    name: "11IG1SFRES3",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 82.3,
    name: "11IG1SFRES4",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 82.4,
    name: "11IG1SFRES5",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 118.0,
    name: "11IG2PFRES1",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 118.1,
    name: "11IG2PFWE2_3",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 118.2,
    name: "11IG2PFWE2_2",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 118.3,
    name: "11IG2PFWE2_1",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 118.4,
    name: "11IG2PFRES2",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 86.2,
    name: "11IG2SFWE2_1",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 86.3,
    name: "11IG2SFWE2_2",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 92.0,
    name: "11IG2SFWE2_3",
    dataType: "BOOL",
    comment: "E2 �berbr�ckung Schutzkreis Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 92.1,
    name: "11IG2SFW_4",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 92.2,
    name: "11IG2SFW_5",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 118.0,
    name: "11IG2SFRES1",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 118.1,
    name: "11IG2SFRES2",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 118.2,
    name: "11IG2SFRES3",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 118.3,
    name: "11IG2SFRES4",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 118.4,
    name: "11IG2SFRES5",
    dataType: "BOOL",
    comment: "Reserve",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 236.0,
    name: "123456OH1GP1",
    dataType: "BOOL",
    comment: "Achse X Schmierung Ein",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 236.1,
    name: "123456OH1GP2",
    dataType: "BOOL",
    comment: "Achse Z Schmierung Ein",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 236.0,
    name: "123456OH1GP1OK",
    dataType: "BOOL",
    comment: "Achse X Schmierung OK",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 236.1,
    name: "123456OH1GP1Err",
    dataType: "BOOL",
    comment: "Achsen X Schmierung Fehler",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 236.2,
    name: "123456OH1GP2OK",
    dataType: "BOOL",
    comment: "Achse Z Schmierung OK",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 236.3,
    name: "123456OH1GP2Err",
    dataType: "BOOL",
    comment: "Achsen Z Schmierung Fehler",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 238.0,
    name: "123456OH1K01BGE99aR",
    dataType: "BOOL",
    comment: "Thynkers-Absteckung 1 Z-Achse entriegelt",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 238.1,
    name: "123456OH1K01BGE99aV",
    dataType: "BOOL",
    comment: "Buhl-Absteckung 1 Z-Achse entriegelt",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 238.2,
    name: "123456OH1K01BGE99bR",
    dataType: "BOOL",
    comment: "Buhl -Absteckung 2 Z-Achse entriegelt",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 238.3,
    name: "123456OH1K01BGE99bV",
    dataType: "BOOL",
    comment: "Buhl -Absteckung 2 Z-Achse entriegelt",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 2064.0,
    name: "123456OH1AE1TAF1K100",
    dataType: "BOOL",
    comment: "Stellglieder Start",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 2051.0,
    name: "123456OH1AE1BGE1R",
    dataType: "BOOL",
    comment: "X-Achse in Station 3906",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 2051.1,
    name: "123456OH1AE1BGE1V",
    dataType: "BOOL",
    comment: "X-Achse in Station 3906-N",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 2064.0,
    name: "123456OH1AE1TAF1K100K",
    dataType: "BOOL",
    comment: "Kontrolle Stellglieder Start",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 2086.0,
    name: "123456OH1AE2TAF1K100",
    dataType: "BOOL",
    comment: "Stellglieder Start",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 2073.0,
    name: "123456OH1AE2BGE1R",
    dataType: "BOOL",
    comment: "Z-Achse in Grundstellung oben",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 2086.0,
    name: "123456OH1AE2TAF1K100K",
    dataType: "BOOL",
    comment: "Kontrolle Stellglieder Start",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.2,
    name: "123456OH1VI2BGE11aR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.3,
    name: "123456OH1VI2BGE11aV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.4,
    name: "123456OH1VI2BGE11bR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.5,
    name: "123456OH1VI2BGE11bV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.6,
    name: "123456OH1VI2BGE11cR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 554.7,
    name: "123456OH1VI2BGE11cV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.0,
    name: "123456OH1VI2BGE12aR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.1,
    name: "123456OH1VI2BGE12aV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.2,
    name: "123456OH1VI2BGE12bR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.3,
    name: "123456OH1VI2BGE12bV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.4,
    name: "123456OH1VI2BGE13aR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.5,
    name: "123456OH1VI2BGE13aV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.6,
    name: "123456OH1VI2BGE13bR",
    dataType: "BOOL",
    comment: "Spannzylinder zur�ck",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 555.7,
    name: "123456OH1VI2BGE13bV",
    dataType: "BOOL",
    comment: "Spannzylinder vorn",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 557.4,
    name: "123456OH1VI2BGT13",
    dataType: "BOOL",
    comment: "Teilkontrolle Seitenteil innen",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 557.6,
    name: "123456OH1VI2BGT12",
    dataType: "BOOL",
    comment: "Teilkontrolle Seitenteil innen",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 557.7,
    name: "123456OH1VI2BGT11",
    dataType: "BOOL",
    comment: "Teilkontrolle Seitenteil innen",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 244.0,
    name: "123456OH1BGS10V",
    dataType: "BOOL",
    comment: "Handligs-Einheit",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 0.0,
    name: "1IA1PFK83PIN1",
    dataType: "BOOL",
    comment: "Standmenge",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 0.1,
    name: "1IA1PFK83PIN2",
    dataType: "BOOL",
    comment: "Standmenge",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 2,
    address: 0.2,
    name: "1IA1PFK83PIN3",
    dataType: "BOOL",
    comment: "Standmenge",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 0.7,
    name: "1IA1SFWE7",
    dataType: "BOOL",
    comment: "E7 �berbr�ckung Verriegelung",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 6.1,
    name: "1IA1SFA1",
    dataType: "BOOL",
    comment: "Antriebeschalter",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 1.0,
    name: "1BS1TB1NGIO",
    dataType: "BOOL",
    comment: "Kontrolle Netzger�t in Ordnung",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 1.1,
    name: "1BS1BA1NETZ",
    dataType: "BOOL",
    comment: "Netzkontrolle in Ordnung",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 1.2,
    name: "1BS1BT1",
    dataType: "BOOL",
    comment: "Schranktemperatur in Ordnung",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 1.3,
    name: "1BS1/SIFA",
    dataType: "BOOL",
    comment: "Sammelmeldung kein Sicherungsfall",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 517.6,
    name: "1ED1/SIFA",
    dataType: "BOOL",
    comment: "Sammelmeldung kein Sicherungsfall",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 517.7,
    name: "1ED1TB1NGIO",
    dataType: "BOOL",
    comment: "Kontrolle Netzger�t in Ordnung",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
  {
    operandIdentifier: 1,
    address: 0.1,
    name: "1ES1QB1K",
    dataType: "BOOL",
    comment: "Leistung ist Ein ES-Schrank",
    accessibleFromHmi: false,
    visibleInHmiEngineering: false,
    writableFromHmi: false,
  },
];

export const homeFormSubmitWithIds = homeFormSubmit.map((el, id) => ({
  id,
  ...el,
}));
